service: valence-api
app: valence
#org: your-org-name

custom:
  esbuild:
    config: './esbuild.config.js'
  serverless-offline:
    port: 8003

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  albums:
    handler: functions/albums.albums
    events:
      - http:
          method: get
          path: albums
  artists:
    handler: functions/artists.artists
    events:
      - http:
          method: get
          path: artists
  genius:
    handler: functions/genius.song
    events:
      - http:
          method: get
          path: genius/song
  genius-artist:
    handler: functions/genius-artist.artist
    events:
      - http:
          method: get
          path: genius/artist
  playlists:
    handler: functions/playlists.playlists
    events:
      - http:
          method: get
          path: playlists
